# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import solution_pb2 as solution__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in solution_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SolutionStreamerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamSolutions = channel.stream_unary(
                '/optimizer.SolutionStreamer/StreamSolutions',
                request_serializer=solution__pb2.SolutionUpdate.SerializeToString,
                response_deserializer=solution__pb2.Ack.FromString,
                _registered_method=True)


class SolutionStreamerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamSolutions(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SolutionStreamerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamSolutions': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamSolutions,
                    request_deserializer=solution__pb2.SolutionUpdate.FromString,
                    response_serializer=solution__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'optimizer.SolutionStreamer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('optimizer.SolutionStreamer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SolutionStreamer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamSolutions(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/optimizer.SolutionStreamer/StreamSolutions',
            solution__pb2.SolutionUpdate.SerializeToString,
            solution__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
