# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: solution.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'solution.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esolution.proto\x12\toptimizer\"\x82\x01\n\x0bVariableSet\x12.\n\x04vars\x18\x01 \x03(\x0b\x32 .optimizer.VariableSet.VarsEntry\x1a\x43\n\tVarsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.optimizer.VariableMap:\x02\x38\x01\"p\n\x0bVariableMap\x12\x32\n\x06values\x18\x01 \x03(\x0b\x32\".optimizer.VariableMap.ValuesEntry\x1a-\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"v\n\x08Solution\x12,\n\x0cvariable_map\x18\x01 \x01(\x0b\x32\x16.optimizer.VariableSet\x12\x17\n\x0fobjective_value\x18\x02 \x01(\x01\x12\x10\n\x08\x66\x65\x61sible\x18\x03 \x01(\x08\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"7\n\x0eSolutionUpdate\x12%\n\x08solution\x18\x01 \x01(\x0b\x32\x13.optimizer.Solution\"\x16\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32R\n\x10SolutionStreamer\x12>\n\x0fStreamSolutions\x12\x19.optimizer.SolutionUpdate\x1a\x0e.optimizer.Ack(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'solution_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VARIABLESET_VARSENTRY']._loaded_options = None
  _globals['_VARIABLESET_VARSENTRY']._serialized_options = b'8\001'
  _globals['_VARIABLEMAP_VALUESENTRY']._loaded_options = None
  _globals['_VARIABLEMAP_VALUESENTRY']._serialized_options = b'8\001'
  _globals['_VARIABLESET']._serialized_start=30
  _globals['_VARIABLESET']._serialized_end=160
  _globals['_VARIABLESET_VARSENTRY']._serialized_start=93
  _globals['_VARIABLESET_VARSENTRY']._serialized_end=160
  _globals['_VARIABLEMAP']._serialized_start=162
  _globals['_VARIABLEMAP']._serialized_end=274
  _globals['_VARIABLEMAP_VALUESENTRY']._serialized_start=229
  _globals['_VARIABLEMAP_VALUESENTRY']._serialized_end=274
  _globals['_SOLUTION']._serialized_start=276
  _globals['_SOLUTION']._serialized_end=394
  _globals['_SOLUTIONUPDATE']._serialized_start=396
  _globals['_SOLUTIONUPDATE']._serialized_end=451
  _globals['_ACK']._serialized_start=453
  _globals['_ACK']._serialized_end=475
  _globals['_SOLUTIONSTREAMER']._serialized_start=477
  _globals['_SOLUTIONSTREAMER']._serialized_end=559
# @@protoc_insertion_point(module_scope)
