# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: solution.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'solution.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esolution.proto\x12\toptimizer\"p\n\x0bVariableMap\x12\x32\n\x06values\x18\x01 \x03(\x0b\x32\".optimizer.VariableMap.ValuesEntry\x1a-\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"\x82\x01\n\x0bVariableSet\x12.\n\x04vars\x18\x01 \x03(\x0b\x32 .optimizer.VariableSet.VarsEntry\x1a\x43\n\tVarsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.optimizer.VariableMap:\x02\x38\x01\"\x8a\x01\n\x08Solution\x12,\n\x0cvariable_map\x18\x01 \x01(\x0b\x32\x16.optimizer.VariableSet\x12\x17\n\x0fobjective_value\x18\x02 \x01(\x01\x12\x10\n\x08\x66\x65\x61sible\x18\x03 \x01(\x08\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x12\n\nis_optimal\x18\x05 \x01(\x08\"\x16\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x46\n\x0fSolutionService\x12\x33\n\x0cSendSolution\x12\x13.optimizer.Solution\x1a\x0e.optimizer.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'solution_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VARIABLEMAP_VALUESENTRY']._loaded_options = None
  _globals['_VARIABLEMAP_VALUESENTRY']._serialized_options = b'8\001'
  _globals['_VARIABLESET_VARSENTRY']._loaded_options = None
  _globals['_VARIABLESET_VARSENTRY']._serialized_options = b'8\001'
  _globals['_VARIABLEMAP']._serialized_start=29
  _globals['_VARIABLEMAP']._serialized_end=141
  _globals['_VARIABLEMAP_VALUESENTRY']._serialized_start=96
  _globals['_VARIABLEMAP_VALUESENTRY']._serialized_end=141
  _globals['_VARIABLESET']._serialized_start=144
  _globals['_VARIABLESET']._serialized_end=274
  _globals['_VARIABLESET_VARSENTRY']._serialized_start=207
  _globals['_VARIABLESET_VARSENTRY']._serialized_end=274
  _globals['_SOLUTION']._serialized_start=277
  _globals['_SOLUTION']._serialized_end=415
  _globals['_ACK']._serialized_start=417
  _globals['_ACK']._serialized_end=439
  _globals['_SOLUTIONSERVICE']._serialized_start=441
  _globals['_SOLUTIONSERVICE']._serialized_end=511
# @@protoc_insertion_point(module_scope)
